version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - "9026:3001"
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2-alpine
    env_file:
      - .env
    # ports:
    #   - "5432:5432"
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data